---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# DevBox OS - A developer-focused Silverblue custom image
name: devbox-os
description: DevBox OS - Container-first development environment on Fedora Silverblue

# Base image: Pure Fedora Silverblue (GNOME)
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 43 # Fedora 43 - latest stable

# Module configuration, executed in order
modules:
  # Copy custom system files
  - type: files
    files:
      - source: system
        destination: /

  # DNF packages - Keep minimal for immutable system
  - type: dnf
    repos:
      # RPM Fusion for multimedia codecs
      nonfree: rpmfusion
    install:
      packages:
        # System management tools
        - bootc

        # Essential CLI tools (host shell environment)
        - distrobox
        - fish
        - zsh
        - neovim
        - tmux

        # Container tools
        - podman-compose

        # Multimedia codecs (RPM Fusion)
        - ffmpeg
        - gstreamer1-plugins-bad-free
        - gstreamer1-plugins-bad-freeworld # AAC, etc. (nonfree codecs)
        - gstreamer1-plugins-good
        - gstreamer1-plugins-ugly # Full version (x264, etc.)
        - gstreamer1-libav # FFmpeg backend for GStreamer
        - gstreamer1-plugin-openh264
        - mozilla-openh264

        # AMD GPU support (Mesa/Vulkan/OpenCL)
        - mesa-vulkan-drivers
        - mesa-va-drivers-freeworld # Better AMD hardware acceleration
        - mesa-vdpau-drivers-freeworld # Video decode acceleration
        - rocm-opencl
        - vulkan-tools

        # Fonts
        - fira-code-fonts
        - jetbrains-mono-fonts
        - google-noto-emoji-fonts

        # Virtualization/KVM
        - qemu-kvm
        - libvirt
        - virt-install
        - libvirt-daemon-config-network
        - libvirt-daemon-kvm

        # Thunderbolt/USB4 security
        - bolt

        # Btrfs snapshot management
        - snapper
        - python3-dnf-plugin-snapper

    remove:
      packages:
        # Remove default apps (we'll use Flatpak versions)
        - firefox
        - firefox-langpacks
        - gnome-tour
        - gnome-contacts
        - gnome-maps
        - totem # video player (vlc flatpak instead)
        - rhythmbox # music player

        # Remove toolbox (using distrobox instead)
        - toolbox

        # Remove ffmpeg-free libs (will install full ffmpeg from RPM Fusion)
        - ffmpeg-free
        - libavcodec-free
        - libavdevice-free
        - libavfilter-free
        - libavformat-free
        - libavutil-free
        - libpostproc-free
        - libswresample-free
        - libswscale-free

        # Remove base mesa drivers (will install freeworld versions)
        - mesa-va-drivers
        - mesa-vdpau-drivers

        # Remove gstreamer ugly-free (will install full version)
        - gstreamer1-plugins-ugly-free

  # Default Flatpak applications
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          # Browsers
          - com.brave.Browser
          - org.mozilla.firefox

          # Development
          - com.visualstudio.code
          - io.github.zen_browser.zen

          # Communication
          - org.telegram.desktop
          - org.mozilla.Thunderbird

          # Multimedia
          - org.videolan.VLC
          - com.spotify.Client

          # Utilities
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.gnome.Boxes # virtual machines
          - com.mattjakeman.ExtensionManager # GNOME extensions

      - scope: user

  # Enable systemd services
  - type: systemd
    system:
      enabled:
        - libvirtd.service

  # Custom scripts for post-install configuration
  - type: script
    scripts:
      - setup-distrobox.sh
      - configure-shell.sh
      - setup-kvm.sh
      - setup-snapper.sh

  # Image signing for security
  - type: signing
